### ISSUE TITLE
secret_id_bound_cidrs and token_bound_cidrs broken because vault does not trust X-Forwarded-For header

### ISSUE THREAD

**Issue by davidgubler** [projectsyn/component-vault#8]
Currently it is not possible to use secret_id_bound_cidrs and token_bound_cidrs restrictions on secrets and tokens in any meaningful way, because vault does not "see" the external IP of the client connecting to it; it only "sees" the IP of the load balancer.

As far as I can tell Vault has support for the X-Forwarded-For header, but it does not trust it by default and thus ignores it. The configuration option "x_forwarded_for_authorized_addrs" (https://www.vaultproject.io/docs/configuration/listener/tcp#x_forwarded_for_authorized_addrs) can be used to whitelist IP addresses for which the X-Forwarded-For header is trusted. Thus, the Vault setup configuration should be changed: The x_forwarded_for_authorized_addrs option should be added and it should contain the IP addresses of the load balancers. 

(Note that the discussion here: https://github.com/hashicorp/vault/issues/12334 talks about the configuration option "x_forwarded_for_authorized_cidrs" which is different from the one in the vault documentation, note the suffix _cidrs vs. _addrs. Maybe only one of them works, maybe both work, I don't know).

Now I am not sure if it is somehow possible to get the specific internal load balancer addresses automatically. I would argue though that it should also be OK to white-list the entire 10.x private IP range, since it isn't easily possible to by-pass the load balancers (unless that has been specifically set up).

The context of this request is VSHNOPS-3525. Not being able to use this vault functionality significantly reduces the security of that feature, and it is quite possible that other vault users could profit from working IP address restrictions as well.

Thanks!

## Out of scope

* Migrate existing Synfra Vault setup to component-vault

## Acceptance Criteria

* The difference (if any) between `x_forwarded_for_authorized_cidrs` and `x_forwarded_for_authorized_addrs` is documented in the component docs
* The component allows configuration of `x_forwarded_for_authorized_addrs` or `x_forwarded_for_authorized_cidrs` (both if there's a difference between the two).

**Comment by simu** [comment]
Setting `x_forwarded_for_authorized_addrs = "10.42.0.0/16"` (effectively trusting `X-Forwarded-For` sent by any pod in the cluster) seems to be sufficient to enable parsing of X-Forwarded-For, as I now see "real" client IPs in the Vault audit log.
